### ISSUE TITLE
Availability on BioConda

### ISSUE THREAD

**Issue by lecorguille** [sriramlab/OrientAGraph#1]
Hi @ekmolloy,

I'm managing computing infrastructures in France. One of my colleague request me to install your tool.
For maintainability and reproducibility, we only install tools from Conda (and Singularity).

Have you ever thinking about providing OrientAGraph as a Conda package?

If you start a package on [bioconda](https://bioconda.github.io/), I can help you if you need.

All the best

**Comment by ekmolloy** [comment]
Thanks for your comment - I will look into making a Conda package for this repository! Also, I will release statically compiled binaries for Linux and Mac to make the install easier. -Erin

**Comment by lecorguille** [comment]
Hi,

Is there any progress here?
I can try to produce a Conda package if you didn't find the time.

Can you create a tag within this repo  I will be able to target?

**Comment by ekmolloy** [comment]
Thanks for following up. Another user brought a bug to my attention that can occur when reading input files. I introduced this bug into the code after running our experiments for the preprint, so I am testing that I can replicate our results over today/tomorrow and then I will go ahead and create a tag. Thanks!

**Comment by lecorguille** [comment]
Here is the future Conda recipe https://github.com/bioconda/bioconda-recipes/pull/28733
I just wait for the tag to finalize it!

**Comment by ekmolloy** [comment]
Thank you!

I have created a new branch called "cleanup", and I have finished replicating the results. I am just checking that the new user option (the -score function) is working currently, and then I will add a tag. Sorry for the delay!

**Comment by ekmolloy** [comment]
The first release is now available.

**Comment by lecorguille** [comment]
Hop : https://anaconda.org/bioconda/orientagraph

**Comment by ekmolloy** [comment]
Thank you!
