### ISSUE TITLE
example linked to in readme is missing

### ISSUE THREAD

**Issue by jpjoines** [sriramlab/OrientAGraph#11]
The first paragraph of the OrientAGraph README at https://github.com/sriramlab/OrientAGraph has a "this example" link targeting URL https://github.com/sriramlab/OrientAGraph/blob/main/example/README.md.  That target does not seem to exist:

"404 - page not found
The main branch of OrientAGraph does not contain the path example/README.md."

**Comment by ekmolloy** [comment]
Thanks for the reminder; we have added examples. Please install version 1.2 of OrientAGraph to do the examples because there are new default settings. Let us know if you have any issues.
