### ISSUE TITLE
why I can't get edge -m changed

### ISSUE THREAD

**Issue by huangl07** [sriramlab/OrientAGraph#4]
dear,

I have already used the orientagraph software for my data

but one of my data is ambiguous,

my command is "orientagraph -i pop.tmix.gz -m 5  -o pop.5.5 -k 1000 -bootstrap -global"

but the resule llik file is like this:

"Starting ln(likelihood) with 0 migration events: 71.0333 
Exiting ln(likelihood) with 1 migration events: 81.6075"

I wander know why? 

As I understood ,the -m parameter is equal to the migration events?

**Comment by huangl07** [comment]
[Uploading pop.tmix.gz…]()
you can try the file

**Comment by huangl07** [comment]
not only the -m 5,  -m2 is also no change

**Comment by ekmolloy** [comment]
Your file pop.tmix.gz has allele frequencies for 4 populations. It seems reasonable to me that you would be able to explain the data by adding a single admixture edge (and thus no more admixture edges are added). I recommend reading Mark Lipson's 2020 review (download here: https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.13230), especially checking out Figure 3. Overall, if your model has 4 populations and 5 admixture edges, you probably do not want to use methods based on f-statistics.

**Comment by huangl07** [comment]
thank you，I will read it
